#!/bin/sh

if test -z "$HOL2DK_DIR"
then
    echo "HOL2DK_DIR is not set"
    exit 1
fi

if test -z "$HOLLIGHT_DIR"
then
    echo "HOLLIGHT_DIR is not set"
    exit 1
fi

if test $# -ne 1
then
    echo "usage: `basename $0` FILE"
    echo 'add links to files in the directories $HOL2DK_DIR and $HOLLIGHT_DIR for translating the proofs of FILE'
    exit 1
fi

for ext in prf nbp sig thm pos use
do
   ln -f -s $HOLLIGHT_DIR/$1.$ext
done

for f in theory_hol.dk theory_hol.lp lambdapi.pkg coq.v _CoqProject Makefile
do
    ln -f -s $HOL2DK_DIR/$f
done
