#!/bin/sh

if test -z "$HOL2DK_DIR"
then
    echo "HOL2DK_DIR is not set"
    exit 1
fi

if test -z "$HOLLIGHT_DIR"
then
    echo "HOLLIGHT_DIR is not set"
    exit 1
fi

if test $# -ne 1 -a $# -ne 3
then
    echo "usage: `basename $0` hollight_file.ml [coq_file.v erasing.lp]"
    echo '  hollight_file.ml: path to an ml file relative to $HOLLIGHT_DIR'
    echo '  coq_file.v: coq file imported in all generated coq files'
    echo '  erasing.lp: mappings between lambdapi and coq'
    echo 'in the current directory:'
    echo '- create a file BASE'
    echo '- create a file ROOT_PATH'
    echo '- create a file lambdapi.pkg'
    echo '- create a file _CoqProject'
    echo '- create a file ERASING'
    echo '- add links to coq_file.v and other files in $HOL2DK_DIR and $HOLLIGHT_DIR for translating and checking the proofs of hollight_file'
    exit 1
fi

base=`basename $1 .ml`

echo create BASE ...
echo $base > BASE

root_path=`basename ${2:-HOLLight} .v`
if test $# -gt 1
then
    echo create ROOT_PATH ...
    echo $root_path > ROOT_PATH
fi

echo create lambdapi.pkg ...
echo "package_name = $root_path" > lambdapi.pkg
echo "root_path = $root_path" >> lambdapi.pkg

echo create _CoqProject ...
echo "-R . $root_path ." > _CoqProject

echo create ERASING ...
echo ${3:-$HOL2DK_DIR/erasing.lp} > ERASING

coq_file=${2:-$HOL2DK_DIR/HOLLight.v}
echo ln -f -s $coq_file
ln -f -s $coq_file

for f in theory_hol.dk theory_hol.lp Makefile BIG_FILES
do
    echo ln -f -s $HOL2DK_DIR/$f
    ln -f -s $HOL2DK_DIR/$f
done

for ext in prf nbp sig thm pos use
do
    echo ln -f -s $HOLLIGHT_DIR/$base.$ext
    ln -f -s $HOLLIGHT_DIR/$base.$ext
done
