#!/bin/sh

if test ! -f BASE; then echo "error: file \"BASE\" missing"; exit 1; fi

base=`cat BASE`

for f in `grep -l -e real -e nadd -e axiom_2[1-4] -e dist *.lp | grep -v ${base}_types`
do
    v=${f%.lp}.v
    if ! grep -q '^Require Import coq coq_real\.' $v
    then
        echo patch $v ...
        sed -i -e 's/^Require Import coq\./Require Import coq coq_real./' $v
        sed -i -e 's/: theory_hol.lpo/: coq_real.lpo theory_hol.lpo/' ${f}o.mk
    fi
done
make dep
echo patch vo.mk ...
sed -i -e '1i coq_real.vo: coq.vo' vo.mk
for f in `grep -l ' real ' *.lp | grep -v ${base}_types` lp
do
    sed -i -e 's/ coq_real.lpo//' ${f}o.mk
done
touch vo.mk
