#!/bin/sh

for f in `find . -name \*.v`
do
    if grep -m 1 -q ' R[ )},]' $f
    then
        echo $f
        sed -i -e 's/Require Import HOLLight_Real.HOLLight_Real HOLLight\.$/Require Import HOLLight_Real.HOLLight_Real HOLLight Rdefinitions./' $f
    fi
done
