#!/bin/sh

if test $# -lt 1 -o $# -gt 2; then echo "usage: $0 file.[mh]l"; exit 1; fi

case $1 in
    *.ml) f=${1%.ml};;
    *.hl) f=${1%.hl};;
    *) echo "$1: wrong file extension (should be .ml or .hl)"; exit 1;;
esac

cat << EOF | ocaml
print_endline "------------------------------------------------------------";;
print_endline "#use \"topfind\";;";;
#use "topfind";;
print_endline "------------------------------------------------------------";;
print_endline "#require \"camlp5\";;";;
#require "camlp5";;
print_endline "------------------------------------------------------------";;
print_endline "#load \"camlp5o.cma\";;";;
#load "camlp5o.cma";;
print_endline "------------------------------------------------------------";;
print_endline "#use \"$1\";;";;
#use "$1";;
print_endline "------------------------------------------------------------";;
print_endline "dump_signature();;";;
dump_signature();;
EOF

exit=$?
if test $exit -ne 0; then exit $exit; fi
mv -f signature.dump ${f}_sig.dump
mv -f proofs.dump ${f}_proofs.dump
