#!/bin/sh

if test $# -ne 1; then echo "usage: $0 file.[mh]l"; exit 1; fi

case $1 in
    *.ml) f=${1%.ml};;
    *.hl) f=${1%.hl};;
    *) echo "$1: wrong file extension (should be .ml or .hl)"; exit 1;;
esac

cat << EOF | ocaml
print_endline "------------------------------------------------------------";;
print_endline "#use \"topfind\";;";;
#use "topfind";;
print_endline "------------------------------------------------------------";;
print_endline "#require \"camlp5\";;";;
#require "camlp5";;
print_endline "------------------------------------------------------------";;
print_endline "#load \"camlp5o.cma\";;";;
#load "camlp5o.cma";;
print_endline "------------------------------------------------------------";;
print_endline "#use \"$1\";;";;
#use "$1";;
print_endline "------------------------------------------------------------";;
print_endline "dump_signature \"$f.sig\";;";;
dump_signature "$f.sig";;
EOF

exit=$?
if test -f .dump.prf; then mv -f .dump.prf $f.prf; fi
exit $exit
