#!/bin/sh

if test $# -ne 1
then
    echo "wrong number of arguments"
    echo "usage: $0 hol-light-dir"
    exit 1
fi
dir=$1

if test -f $dir/fusion-bak.ml
then
    echo "$dir/fusion-bak.ml already exists"
    exit 1
else
    echo "cp $dir/fusion.ml $dir/fusion-bak.ml"
    cp $dir/fusion.ml $dir/fusion-bak.ml
    echo "patch $dir/fusion.ml"
    sed -e 's/.*REMOVE.*//' -e 's/Stdlib/Pervasives/g' -e 's/open Lib/needs "lib.ml";;/' -e 's/val dummy_proof : proof//' fusion.ml > $dir/fusion.ml
fi
