#!/bin/sh

if test $# -ne 1
then
    echo "wrong number of arguments"
    echo "usage: $0 hol-light-dir"
    exit 1
fi
dir=$1

if test -f $dir/fusion-bak.ml
then
    echo "$dir/fusion-bak.ml already exists"
    exit 1
else
    echo "cp $dir/fusion.ml $dir/fusion-bak.ml"
    cp $dir/fusion.ml $dir/fusion-bak.ml
    echo "patch $dir/fusion.ml"
    sed -e 's/.*REMOVE.*//' -e 's/Stdlib/Pervasives/g' -e 's/open Lib/needs "lib.ml";;/' -e 's/val dummy_proof : proof//' fusion.ml > $dir/fusion.ml
fi

if test -f $dir/bool-bak.ml
then
    echo "$dir/bool-bak.ml already exists"
    exit 1
else
    echo "cp $dir/bool.ml $dir/bool-bak.ml"
    cp $dir/bool.ml $dir/bool-bak.ml
    echo "patch $dir/bool.ml"
    sed -e 's/.*REMOVE.*//' bool.ml > $dir/bool.ml
fi

# usage: cp_file f
cp_file() {
    if test -f $dir/$1
    then
        echo "$dir/$1 already exists"
        exit 1
    else
        echo "create $dir/$1"
        sed -e 's/.*REMOVE.*//' -e 's/^open .*//' $1 > $dir/$1
    fi
}

cp_file xprelude.ml
cp_file xlib.ml
cp_file xnames.ml
