#!/bin/sh

if test $# -ne 2; then echo "usage: `basename $0` BASE MAX"; exit 1; fi

b=$1
max=$2

n=`ls $b.lp ${b}_part_*.lp | wc -l`
if test $n -eq 0; then echo "error: $b.lp does not exist"; exit 1; fi
