#!/bin/sh

if test $# -ne 2; then echo "usage: `basename $0` BASE MAX"; exit 1; fi

b=$1
max=$2

n=`ls ${b}_part_*.lp $b.lp | wc -l`
if test $n -eq 0; then echo "error: $b.lp does not exist"; exit 1; fi
n=`expr $n - 1`

if test ! -f $b.lp; then echo "error: $b.lp does not exist"; exit 1; fi
h=${b}_header.lp
echo "generate $h ..."
awk '/^require /{print;next}{nextfile}' $b.lp > $h
sed -i -e "/^require open hol-light.${b}_part_/d" $h

p=${b}_proofs.lp
echo "generate $p ..."
cat `ls -v ${b}_part_*.lp` $b.lp > $p
sed -i -e '/^require /d' -e 's/^private /opaque /' $p
rm -f ${b}_part_*.lp $b.lp

echo "generate $b.lp.bak ..."
cat $h $p > $b.lp.bak

echo "split $p ..."
split --numeric-suffixes=1 -a5 -l$max $p
n=`ls x* | wc -l`

for p in `ls x*`
do
    k=`expr ${p#x} + 0` # remove leading zeros
    if test $k -eq $n; then s=''; else s=_part_$k; fi
    g=$b$s.lp
    echo "generate $g ..."
    if test $k -gt 1; then i=`expr $k - 1`; sed -i -e "\$a require open hol-light.${b}_part_$i;" $h; fi
    cat $h $p > $g
    rm -f $p
done
rm -f $h

echo "warning: all theorems are exported"
