#!/bin/sh

usage() { echo "usage: `basename $0` FILE.lp INTEGER"; }
error() { echo "error: $1"; usage; exit 1; }

echo "`basename $0` $* ..."

case "$1" in
    -h|--help) if test $# -eq 1; then usage; exit 0; else error "wrong number of arguments"; fi;;
esac

if test $# -ne 2; then error "wrong number of arguments"; fi

case $1 in
    *.lp) b=${1%.lp};;
    *) echo "error: not a .lp file"; exit 1;;
esac

max=$2

parts=`find . -name "${b}_part_*.lp"`
parts="$parts $b.lp"
n=`ls $parts | wc -l`
if test $n -eq 0; then echo "error: $b.lp does not exist"; exit 1; fi
n=`expr $n - 1`

if test ! -f $b.lp; then echo "error: $b.lp does not exist"; exit 1; fi
h=${b}_header.lp
echo "generate $h ..."
awk '/^require /{print;next}{nextfile}' $b.lp > $h
sed -i -e "/^require open hol-light.${b}_part_/d" $h

p=${b}_proofs.lp
echo "generate $p ..."
cat `ls -v $parts` > $p
sed -i -e '/^require /d' -e 's/^private /opaque /' $p
rm -f $parts

echo "generate $b.lp.bak ..."
cat $h $p > $b.lp.bak

echo "split $p ..."
split --numeric-suffixes=1 -a5 -l$max $p
rm -f $p

n=`ls x* | wc -l`
for p in `ls x*`
do
    k=`expr ${p#x} + 0` # remove leading zeros
    if test $k -eq $n; then s=''; else s=_part_$k; fi
    g=$b$s.lp
    echo "generate $g ..."
    if test $k -gt 1; then i=`expr $k - 1`; sed -i -e "\$a require open hol-light.${b}_part_$i;" $h; fi
    cat $h $p > $g
    rm -f $p
done
rm -f $h

echo "warning: all theorems are exported"
echo "do \"make $b.lp\" to optimize this"
