#!/bin/sh

if test "$1" = "-y"
then
    opt=''
    shift
else
    opt=' -i'
fi

if test $# -ne 1
then
    echo "wrong number of arguments"
    echo "usage: $0 hol-light-dir"
    exit 1
fi

dir=$1

if test -f $dir/fusion-bak.ml
then
    echo "mv$opt $dir/fusion-bak.ml $dir/fusion.ml"
    mv$opt $dir/fusion-bak.ml $dir/fusion.ml
else
    echo "$dir/fusion-bak.ml does not exist"
fi

if test -f $dir/bool-bak.ml
then
    echo "mv$opt $dir/bool-bak.ml $dir/bool.ml"
    mv$opt $dir/bool-bak.ml $dir/bool.ml
else
    echo "$dir/bool-bak.ml does not exist"
fi

echo "rm$opt $dir/xnames.ml"
rm$opt $dir/xnames.ml
