#!/bin/sh

if test $# -ne 1
then
    echo "wrong number of arguments"
    echo "usage: $0 hol-light-dir"
    exit 1
fi
dir=$1

if test -f $dir/fusion-bak.ml
then
    echo "restore fusion.ml"
    mv $dir/fusion-bak.ml $dir/fusion.ml
else
    echo "$dir/fusion-bak.ml does not exist"
    exit 1
fi
